In [1]:
import numpy as np

In [2]:
# An arbitrary vector Nx1 -- in our example 8x1

N = 8
x = np.array([
    1.5+2.6j,
    2.7+7.3j,
    1.7+4.0j,
    4.1+9.1j,
    3.9+1.4j,
    2.9+4.8j,
    3.0+1.6j,
    7.3+2.1j
])

## Fast Forier Transform

### Definition of Fast Fourier Transform

\begin{equation} \omega(m) = \overset{N}{\sum_{j = 1}} e^{-i \frac{2 \pi}{N}(j - 1)(m - 1)} x(j) \end{equation}

where x(j) is a matrix

In [79]:
%%time
y = np.fft.fft(x)
y

CPU times: user 372 µs, sys: 57 µs, total: 429 µs
Wall time: 383 µs


array([27.1       +32.9j       ,  8.83883476 +1.72218254j,
        1.6        +4.2j       , -0.20380592 +5.48614357j,
       -6.9       -13.7j       , -8.83883476 +3.27781746j,
       -0.2        -7.4j       , -9.39619408 -5.68614357j])

In [80]:
%%time
# Initiating two arrays to store results (Memory pre-allocation)
yH = np.zeros(N, dtype=complex)
jJ = np.zeros(N)

for i in range(N):
    jJ[i] = i
    
""" 1)
>>> jJ
array([0., 1., 2., 3., 4., 5., 6., 7.])
"""
    
for m in range(N):
    """ 2)
    >>> m * jJ
    0 * [0. 1. 2. 3. 4. 5. 6. 7.] = [0. 0. 0. 0. 0. 0. 0. 0.]
    1 * [0. 1. 2. 3. 4. 5. 6. 7.] = [0. 1. 2. 3. 4. 5. 6. 7.]

    ...

    7 * [0. 1. 2. 3. 4. 5. 6. 7.] = [ 0.  7. 14. 21. 28. 35. 42. 49.]
    """
    
    yH[m] = np.sum(np.exp((-1j * 2.0 * np.pi / N) * m * jJ) * x)
    
yH

CPU times: user 643 µs, sys: 79 µs, total: 722 µs
Wall time: 662 µs


array([27.1       +32.9j       ,  8.83883476 +1.72218254j,
        1.6        +4.2j       , -0.20380592 +5.48614357j,
       -6.9       -13.7j       , -8.83883476 +3.27781746j,
       -0.2        -7.4j       , -9.39619408 -5.68614357j])

## Inverse Fast Forier Transform

In [68]:
%%time
x = np.fft.ifft(y)
x

CPU times: user 300 µs, sys: 91 µs, total: 391 µs
Wall time: 338 µs


array([1.5+2.6j, 2.7+7.3j, 1.7+4.j , 4.1+9.1j, 3.9+1.4j, 2.9+4.8j,
       3. +1.6j, 7.3+2.1j])

In [69]:
%%time
# implemeting IFFT explicitly
xH = np.zeros(N, dtype=complex) 
for m in range(N):
    xH[m]= np.sum(np.exp((1j * 2.0 * np.pi / N) * m * jJ) * y) / N 

xH

CPU times: user 474 µs, sys: 54 µs, total: 528 µs
Wall time: 489 µs


array([1.5+2.6j, 2.7+7.3j, 1.7+4.j , 4.1+9.1j, 3.9+1.4j, 2.9+4.8j,
       3. +1.6j, 7.3+2.1j])